/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/expense/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지출 기록 작성
         * @description 유저가 하루일과동안 쓴 지출목록을 작성합니다.
         */
        post: operations["registerExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/category_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 카테고리 직접추가
         * @description 유저가 직접 카테고리를 추가합니다.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/update_record/{expenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 지출 기록 수정
         * @description 유저가 작성한 지출 기록을 수정합니다.
         */
        patch: operations["updateExpense"];
        trace?: never;
    };
    "/api/expense/remind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 소비기록 회고
         * @description 유저가 하루일과동안 쓴 지출기록에 소비회고를 추가적으로 남깁니다.
         */
        patch: operations["remindExpense"];
        trace?: never;
    };
    "/api/expense/category_update/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 카테고리 수정
         * @description 유저가 직접 카테고리를 수정합니다.
         */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/api/expense/weekly_detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주간 분석 상세 리포트 조회
         * @description 특정 주차의 감정 분석, 만족도 통계, TOP 3 지출 내역 등 상세 데이터를 조회합니다.
         */
        get: operations["getWeeklyDetailReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/summary_record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메인화면 분석 리포트 조회
         * @description 이번 달 총 소비 금액과 지난주 주간 분석 리포트를 한 번에 조회합니다.
         */
        get: operations["getSummaryRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/daily_satisfaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 일별 종합 소비 만족도 조회
         * @description 당일 모든 지출에 대한 회고가 완료된 경우, 전체 만족도 평균을 문구로 반환합니다.
         */
        get: operations["getDailyAverageSatisfaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 일별 지출 내역 조회
         * @description 특정 날짜의 지출 내역과 월간 총액을 조회합니다.
         */
        get: operations["getDailyExpense"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/category_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카테고리 조회
         * @description 지출을 쓰기 전에 사용자가 선택할 카테고리 리스트(기본 7종 + 커스텀)를 서버에서 내려줘야 합니다.
         */
        get: operations["getCategoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kakao/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카카오 로그인 콜백
         * @description 카카오 인가 코드를 통해 로그인을 진행하고 JWT 및 유저 정보를 반환한다.
         */
        get: operations["kakaoCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴
         * @description 현재 로그인한 유저의 정보를 삭제한다.
         */
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ExpenseDetailsDTO: {
            /** Format: int32 */
            amount: number;
            /** Format: date */
            expendedAt: string;
            /** Format: int64 */
            categoryId: number;
            usageHistory: string;
            /** @enum {string} */
            emotionType: "기분 전환" | "그냥 저냥" | "필수템" | "홀린 듯이" | "살기 위해";
        };
        ApiResponseLong: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            /** Format: int64 */
            result?: number;
        };
        CategoryDetailsDTO: {
            name?: string;
        };
        ExpenseRemindRequestDTO: {
            /** Format: int64 */
            expenseId?: number;
            /** @enum {string} */
            evaluationType?: "VERY_SATISFIED" | "SATISFIED" | "NORMAL" | "DISAPPOINTED" | "VERY_DISAPPOINTED";
        };
        CategoryUpdateRequestDTO: {
            name: string;
        };
        EmotionSummary: {
            emotionDescription?: string;
            /** Format: int64 */
            totalAmount?: number;
            /** Format: int64 */
            count?: number;
        };
        EvaluationSummary: {
            /** @enum {string} */
            evaluationType?: "VERY_SATISFIED" | "SATISFIED" | "NORMAL" | "DISAPPOINTED" | "VERY_DISAPPOINTED";
            /** Format: int64 */
            count?: number;
            /** Format: int64 */
            totalAmount?: number;
        };
        ExpenseSimpleResponse: {
            usageHistory?: string;
            /** Format: int64 */
            amount?: number;
        };
        WeeklyDetailReportResponse: {
            weekRange?: string;
            topEmotion?: components["schemas"]["EmotionSummary"];
            inAvarageEvaluation?: string;
            evaluationSummaries?: components["schemas"]["EvaluationSummary"][];
            top3Expenses?: components["schemas"]["ExpenseSimpleResponse"][];
            /** Format: int64 */
            emotionTotalAmount?: number;
            /** Format: int64 */
            weeklyTotalCount?: number;
            /** Format: int64 */
            weeklyTotalAmount?: number;
        };
        MonthlyReportSummaryResponse: {
            month?: string;
            /** Format: int64 */
            totalAmount?: number;
            isOpened?: boolean;
        };
        SummaryRecordResponse: {
            monthlyReport?: components["schemas"]["MonthlyReportSummaryResponse"];
            weeklyReport?: components["schemas"]["WeeklyReportResponse"];
        };
        WeeklyReportResponse: {
            weekRange?: string;
            /** Format: int64 */
            weeklyTotalAmount?: number;
            topEmotion?: components["schemas"]["EmotionSummary"];
            emotionDetails?: components["schemas"]["EmotionSummary"][];
        };
        ApiResponseString: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: string;
        };
        DailyExpenseResponseDTO: {
            /** Format: date */
            date?: string;
            /** Format: int64 */
            monthlyTotalAmount?: number;
            expenses?: components["schemas"]["ExpenseListDTO"][];
        };
        ExpenseListDTO: {
            /** Format: int64 */
            expenseId?: number;
            /** Format: int32 */
            amount?: number;
            usageHistory?: string;
            categoryName?: string;
            /** @enum {string} */
            emotionType?: "기분 전환" | "그냥 저냥" | "필수템" | "홀린 듯이" | "살기 위해";
            /** @enum {string} */
            evaluationType?: "VERY_SATISFIED" | "SATISFIED" | "NORMAL" | "DISAPPOINTED" | "VERY_DISAPPOINTED";
        };
        ApiResponseListCategoryListResponseDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CategoryListResponseDTO"][];
        };
        CategoryListResponseDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        AuthResponse: {
            accessToken?: string;
            user?: components["schemas"]["UserInfo"];
        };
        UserInfo: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            /** Format: int32 */
            age?: number;
            gender?: string;
            region?: string;
            type?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerExpense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseDetailsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryDetailsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    updateExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expenseId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseDetailsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    remindExpense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseRemindRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    getWeeklyDetailReport: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeeklyDetailReportResponse"];
                };
            };
        };
    };
    getSummaryRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SummaryRecordResponse"];
                };
            };
        };
    };
    getDailyAverageSatisfaction: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getDailyExpense: {
        parameters: {
            query: {
                year: number;
                month: number;
                day: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DailyExpenseResponseDTO"];
                };
            };
        };
    };
    getCategoryList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCategoryListResponseDTO"];
                };
            };
        };
    };
    kakaoCallback: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
