/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/inquiry/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 1:1 문의 메일 발송
         * @description 사용자가 작성한 문의 내용을 관리자 이메일로 전송합니다.
         */
        post: operations["sendInquiry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지출 기록 작성
         * @description 유저가 하루일과동안 쓴 지출목록을 작성합니다.
         */
        post: operations["registerExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/category_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 카테고리 직접추가
         * @description 유저가 직접 카테고리를 추가합니다.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급 API
         * @description 헤더의 RefreshToken(Bearer 형기)으로 토큰을 재발급합니다.
         */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 공통 로그아웃
         * @description 카카오/애플 로그인 방식에 관계없이 현재 사용자를 로그아웃 처리합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kakao/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 카카오 회원가입
         * @description 임시 토큰을 이용해 카카오 가입을 완료하고 정식 JWT를 발급한다.
         */
        post: operations["kakaoSignup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kakao/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 카카오 로그인/체크
         * @description 카카오 토큰으로 기존 유저인지 확인한다. 신규 유저면 newUser: true와 임시 토큰을 반환한다.
         */
        post: operations["kakaoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/apple/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 애플 회원가입 완료
         * @description 약관 동의 후 임시 토큰을 전달받아 실제 회원가입(DB 저장)을 처리하고 서비스 토큰을 발급합니다.
         */
        post: operations["appleSignup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/apple/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 애플 로그인 체크
         * @description 애플 OAuth 코드를 받아 가입 여부를 확인합니다. 신규 유저라면 임시 토큰을, 기존 유저라면 서비스 토큰을 반환합니다.
         */
        post: operations["appleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/apple/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 애플 서버 알림 처리
         * @description 애플 서버에서 전송된 알림을 처리합니다.
         */
        post: operations["handleAppleNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/remind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["completeRemindOnboarding"];
        trace?: never;
    };
    "/api/onboarding/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["completeHomeOnboarding"];
        trace?: never;
    };
    "/api/onboarding/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["completeCategoryOnboarding"];
        trace?: never;
    };
    "/api/expense/update_record/{expenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 지출 기록 수정
         * @description 유저가 작성한 지출 기록을 수정합니다.
         */
        patch: operations["updateExpense"];
        trace?: never;
    };
    "/api/expense/report_arrivals/{year}/{month}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 월별 분석 리포트 확인 처리
         * @description 유저가 특정 월의 분석 리포트를 확인했음을 기록합니다.
         */
        patch: operations["checkReport"];
        trace?: never;
    };
    "/api/expense/remind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 소비기록 회고
         * @description 유저가 하루일과동안 쓴 지출기록에 소비회고를 추가적으로 남깁니다.
         */
        patch: operations["remindExpenses"];
        trace?: never;
    };
    "/api/expense/category_update/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 카테고리 수정
         * @description 유저가 직접 카테고리를 수정합니다.
         */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/api/alerts/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 알림 수신 동의 상태 변경
         * @description 유저의 알림 수신 허용/거부 상태를 업데이트합니다.
         */
        patch: operations["updateAlarmStatus"];
        trace?: never;
    };
    "/api/alerts/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 알림 전체 읽음 처리
         * @description 읽지 않은 모든 알림을 읽음 상태로 변경합니다.
         */
        patch: operations["markAllAsRead"];
        trace?: never;
    };
    "/api/alerts/fcm-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * FCM 토큰 업데이트(등록)
         * @description 로그인 직후 기기의 FCM 토큰을 서버에 등록합니다.
         */
        patch: operations["updateFcmToken"];
        trace?: never;
    };
    "/api/weekly-reports/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주간 리포트 - 회고별 소비 내역 상세 조회
         * @description 선택한 마음 항목에 해당하는 지출만 필터링한 뒤, 그 안에서 회고별로 소비 상세 내역을 조회합니다.
         */
        get: operations["getWeeklyExpenseDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/weekly_detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주간 분석 상세 리포트 조회
         * @description 특정 주차의 감정 분석, 만족도 통계, TOP 3 지출 내역 등 상세 데이터를 조회합니다.
         */
        get: operations["getWeeklyDetailReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/total_open_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 월 + 주차별 open 상태 통합 조회
         * @description 특정 월의 총 지출액, 주차별 리포트 오픈 여부, 월간 리포트 오픈 여부를 한 번에 조회합니다.
         */
        get: operations["getTotalOpenStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/summary_record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메인화면 분석 리포트 조회
         * @description 이번 달 총 소비 금액과 지난주 주간 분석 리포트를 한 번에 조회합니다.
         */
        get: operations["getSummaryRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/retrospect-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회고 필요 지출 내역 조회
         * @description 특정 날짜의 지출 중 아직 회고(만족도 조사)가 완료되지 않은 내역만 리스트로 조회합니다.
         */
        get: operations["getRetrospectList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/report_arrivals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 분석 리포트 도착 알림 카드 조회
         * @description 생성한 월별 분석 리포트 알림 카드 목록을 반환합니다. 확인한 리포트는 isChecked=true로
         *       표시됩니다. 이전 달 미확인과 무관하게 최신 리포트도 노출됩니다.
         */
        get: operations["getReportArrivals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/monthly_totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 월별 지출 총액 조회
         * @description 소비 기록이 존재하는 모든 달의 지출 총액 목록을 최신순으로 조회합니다.
         */
        get: operations["getMonthlyTotalList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/daily_satisfaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 일별 종합 소비 만족도 조회
         * @description 당일 모든 지출에 대한 회고가 완료된 경우, 전체 만족도 평균을 문구로 반환합니다.
         */
        get: operations["getDailyAverageSatisfaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 메인화면 일별 지출내역 조회
         * @description 특정 날짜의 지출 내역과 월간 총액을 조회합니다.
         */
        get: operations["getDailyExpense"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/category_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카테고리 조회
         * @description 지출을 쓰기 전에 사용자가 선택할 카테고리 리스트(기본 7종 + 커스텀)를 서버에서 내려줘야 합니다.
         */
        get: operations["getCategoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 특정 월의 총 소비액 및 일별 지출 합계 반환
         * @description 특정 월의 총 소비액과 일별 지출 합계를 조회합니다.
         */
        get: operations["getExpenseCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 알림 목록 조회
         * @description 유저의 알림 목록을 최신순으로 조회합니다.
         */
        get: operations["getAlertList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/unread-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 읽지 않은 알림 존재 여부 확인
         * @description 빨간 점(Badge) 표시 여부
         */
        get: operations["hasUnreadAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense/delete/{expenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 지출 기록 삭제
         * @description 조회된 리스트의 expenseId를 사용하여 기록을 삭제합니다.
         */
        delete: operations["deleteExpense"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴
         * @description 현재 로그인한 유저의 정보를 삭제한다.
         */
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InquiryRequest: {
            content?: string;
            userEmail?: string;
        };
        ApiResponseString: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: string;
        };
        ExpenseDetailsDTO: {
            /** Format: int32 */
            amount: number;
            /** Format: date */
            expendedAt: string;
            /** Format: int64 */
            categoryId: number;
            usageHistory: string;
            /** @enum {string} */
            emotionType: "기분 전환" | "그냥저냥" | "필수템" | "홀린 듯이" | "살기 위해";
        };
        ApiResponseIdResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["IdResponse"];
        };
        IdResponse: {
            /** Format: int64 */
            id?: number;
        };
        CategoryDetailsDTO: {
            name?: string;
            /** @enum {string} */
            icon?: "cook" | "coffee" | "credit" | "book" | "beauty" | "beer" | "shopping" | "camera" | "cup";
        };
        ApiResponseCategoryIdResponseDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CategoryIdResponseDTO"];
        };
        CategoryIdResponseDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            icon?: "cook" | "coffee" | "credit" | "book" | "beauty" | "beer" | "shopping" | "camera" | "cup";
        };
        ApiResponseTokenReissueResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["TokenReissueResultDTO"];
        };
        TokenReissueResultDTO: {
            accessToken?: string;
            refreshToken?: string;
        };
        ApiResponseAuthResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["AuthResponse"];
        };
        AuthResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
            accessToken?: string;
            refreshToken?: string;
            type?: string;
            homeOnboarding?: boolean;
            categoryOnboarding?: boolean;
            remindOnboarding?: boolean;
            isNewUser?: boolean;
            hasExpense?: boolean;
        };
        ApiResponseAppleUserResponseDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["AppleUserResponseDTO"];
        };
        AppleUserResponseDTO: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
            accessToken?: string;
            refreshToken?: string;
            appleSub?: string;
            homeOnboarding?: boolean;
            categoryOnboarding?: boolean;
            remindOnboarding?: boolean;
            isNewUser?: boolean;
            hasExpense?: boolean;
        };
        ApiResponseMapStringBoolean: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: {
                [key: string]: boolean;
            };
        };
        ExpenseRemindRequestDTO: {
            /** Format: int64 */
            expenseId?: number;
            /** @enum {string} */
            evaluationType?: "VERY_SATISFIED" | "SATISFIED" | "NORMAL" | "DISAPPOINTED" | "VERY_DISAPPOINTED";
        };
        ApiResponseListIdResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["IdResponse"][];
        };
        CategoryUpdateRequestDTO: {
            name: string;
            /** @enum {string} */
            icon?: "cook" | "coffee" | "credit" | "book" | "beauty" | "beer" | "shopping" | "camera" | "cup";
        };
        ApiResponseWeeklyExpenseDetailResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["WeeklyExpenseDetailResponse"];
        };
        EvaluationGroupResponse: {
            /** Format: int32 */
            stepNumber?: number;
            evaluationTitle?: string;
            /** Format: int32 */
            groupCount?: number;
            /** Format: int64 */
            groupTotalAmount?: number;
            expenses?: components["schemas"]["ExpenseItemResponse"][];
        };
        ExpenseItemResponse: {
            usageHistory?: string;
            categoryName?: string;
            /** Format: int64 */
            amount?: number;
        };
        WeeklyExpenseDetailResponse: {
            weekRange?: string;
            emotionTitle?: string;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int64 */
            totalAmount?: number;
            evaluationGroups?: components["schemas"]["EvaluationGroupResponse"][];
        };
        ApiResponseWeeklyDetailReportResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["WeeklyDetailReportResponse"];
        };
        EmotionSummary: {
            emotionDescription?: string;
            /** Format: int64 */
            totalAmount?: number;
            /** Format: int64 */
            count?: number;
            feedbackMessage?: string;
        };
        EvaluationSummary: {
            /** @enum {string} */
            evaluationType?: "VERY_SATISFIED" | "SATISFIED" | "NORMAL" | "DISAPPOINTED" | "VERY_DISAPPOINTED";
            /** Format: int64 */
            count?: number;
            /** Format: int64 */
            totalAmount?: number;
        };
        ExpenseSimpleResponse: {
            usageHistory?: string;
            /** Format: int64 */
            amount?: number;
        };
        WeeklyDetailReportResponse: {
            weekRange?: string;
            emotionFeedbackMessage?: string;
            topEmotion?: components["schemas"]["EmotionSummary"];
            evaluationFeedbackMessage?: string;
            evaluationSummaries?: components["schemas"]["EvaluationSummary"][];
            emotionDetails?: components["schemas"]["EmotionSummary"][];
            top3Expenses?: components["schemas"]["ExpenseSimpleResponse"][];
            /** Format: int64 */
            emotionTotalAmount?: number;
            /** Format: int64 */
            weeklyTotalCount?: number;
            /** Format: int64 */
            weeklyTotalAmount?: number;
        };
        ApiResponseTotalOpenStatusResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["TotalOpenStatusResponse"];
        };
        TotalOpenStatusResponse: {
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            month?: number;
            /** Format: int64 */
            totalAmount?: number;
            weeklyReports?: components["schemas"]["WeeklyOpenStatus"][];
            monthlyIsOpened?: boolean;
        };
        WeeklyOpenStatus: {
            /** Format: int32 */
            week?: number;
            isOpened?: boolean;
        };
        ApiResponseSummaryRecordResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["SummaryRecordResponse"];
        };
        MonthlyReportSummaryResponse: {
            year?: string;
            month?: string;
            /** Format: int64 */
            totalAmount?: number;
            isOpened?: boolean;
        };
        SummaryRecordResponse: {
            monthlyReport?: components["schemas"]["MonthlyReportSummaryResponse"];
            weeklyReports?: components["schemas"]["WeeklyReportResponse"][];
        };
        WeeklyReportResponse: {
            weekRange?: string;
            weekPeriod?: string;
            /** Format: int64 */
            weeklyTotalAmount?: number;
            topEmotion?: components["schemas"]["EmotionSummary"];
            emotionDetails?: components["schemas"]["EmotionSummary"][];
        };
        ApiResponseListExpenseResponseDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ExpenseResponseDTO"][];
        };
        ExpenseResponseDTO: {
            /** Format: int64 */
            expenseId?: number;
            /** Format: date */
            date?: string;
            /** @enum {string} */
            categoryIconType?: "cook" | "coffee" | "credit" | "book" | "beauty" | "beer" | "shopping" | "camera" | "cup";
            usageHistory?: string;
            categoryName?: string;
            /** Format: int64 */
            amount?: number;
            emotionType?: string;
        };
        ApiResponseListMonthlyReportArrivalResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MonthlyReportArrivalResponse"][];
        };
        MonthlyReportArrivalResponse: {
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            month?: number;
            isChecked?: boolean;
        };
        ApiResponseListMonthlyReportSummaryResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MonthlyReportSummaryResponse"][];
        };
        ApiResponseDailyExpenseResponseDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["DailyExpenseResponseDTO"];
        };
        DailyExpenseResponseDTO: {
            /** Format: date */
            date?: string;
            /** Format: int64 */
            monthlyTotalAmount?: number;
            bannerMessage?: string;
            bannerSubMessage?: string;
            hasAnyExpense?: boolean;
            expenses?: components["schemas"]["ExpenseListDTO"][];
            retrospectCompleted?: boolean;
        };
        ExpenseListDTO: {
            /** Format: int64 */
            expenseId?: number;
            /** Format: int32 */
            amount?: number;
            usageHistory?: string;
            categoryName?: string;
            /** @enum {string} */
            categoryIconType?: "cook" | "coffee" | "credit" | "book" | "beauty" | "beer" | "shopping" | "camera" | "cup";
            /** @enum {string} */
            emotionType?: "기분 전환" | "그냥저냥" | "필수템" | "홀린 듯이" | "살기 위해";
            /** @enum {string} */
            evaluationType?: "VERY_SATISFIED" | "SATISFIED" | "NORMAL" | "DISAPPOINTED" | "VERY_DISAPPOINTED";
        };
        ApiResponseListCategoryListResponseDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CategoryListResponseDTO"][];
        };
        CategoryListResponseDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            icon?: "cook" | "coffee" | "credit" | "book" | "beauty" | "beer" | "shopping" | "camera" | "cup";
        };
        ApiResponseCalendarResponseDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CalendarResponseDTO"];
        };
        CalendarResponseDTO: {
            /** Format: int64 */
            totalAmount?: number;
            dailyAmount?: components["schemas"]["DailyAmountDTO"][];
        };
        DailyAmountDTO: {
            /** Format: date */
            date?: string;
            /** Format: int64 */
            dayAmount?: number;
        };
        AlertResponseDTO: {
            /** Format: int64 */
            alertId?: number;
            /** @enum {string} */
            alertType?: "RETROSPECT" | "WEEKLY_REPORT" | "SERVICE_NOTICE";
            title?: string;
            message?: string;
            redirectUrl?: string;
            isRead?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseListAlertResponseDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["AlertResponseDTO"][];
        };
        ApiResponseBoolean: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sendInquiry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InquiryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    registerExpense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseDetailsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIdResponse"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryDetailsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryIdResponseDTO"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header: {
                RefreshToken: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenReissueResultDTO"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    kakaoSignup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    kakaoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    appleSignup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAppleUserResponseDTO"];
                };
            };
        };
    };
    appleLogin: {
        parameters: {
            query: {
                code: string;
                platform?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAppleUserResponseDTO"];
                };
            };
        };
    };
    handleAppleNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    completeRemindOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    completeHomeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    completeCategoryOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    updateExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expenseId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseDetailsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIdResponse"];
                };
            };
        };
    };
    checkReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringBoolean"];
                };
            };
        };
    };
    remindExpenses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseRemindRequestDTO"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListIdResponse"];
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryIdResponseDTO"];
                };
            };
        };
    };
    updateAlarmStatus: {
        parameters: {
            query: {
                isAlarmOn: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    markAllAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    updateFcmToken: {
        parameters: {
            query: {
                fcmToken: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getWeeklyExpenseDetails: {
        parameters: {
            query: {
                start: string;
                end: string;
                emotionType: "기분 전환" | "그냥저냥" | "필수템" | "홀린 듯이" | "살기 위해";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWeeklyExpenseDetailResponse"];
                };
            };
        };
    };
    getWeeklyDetailReport: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWeeklyDetailReportResponse"];
                };
            };
        };
    };
    getTotalOpenStatus: {
        parameters: {
            query: {
                year: number;
                month: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTotalOpenStatusResponse"];
                };
            };
        };
    };
    getSummaryRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSummaryRecordResponse"];
                };
            };
        };
    };
    getRetrospectList: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListExpenseResponseDTO"];
                };
            };
        };
    };
    getReportArrivals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMonthlyReportArrivalResponse"];
                };
            };
        };
    };
    getMonthlyTotalList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMonthlyReportSummaryResponse"];
                };
            };
        };
    };
    getDailyAverageSatisfaction: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getDailyExpense: {
        parameters: {
            query: {
                year: number;
                month: number;
                day: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDailyExpenseResponseDTO"];
                };
            };
        };
    };
    getCategoryList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCategoryListResponseDTO"];
                };
            };
        };
    };
    getExpenseCalendar: {
        parameters: {
            query: {
                year: number;
                month: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCalendarResponseDTO"];
                };
            };
        };
    };
    getAlertList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAlertResponseDTO"];
                };
            };
        };
    };
    hasUnreadAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBoolean"];
                };
            };
        };
    };
    deleteExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expenseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
}
