import type { ReportDetailVM } from './reportDetailTypes';

// TODO: API 연동 시 제거
export const MOCK_REPORT_DETAIL: ReportDetailVM = {
  periodLabel: '2026년 1월 2주차',
  subtitleLine: '필수템을 위한 소비에서 가장 많이 소비했고,',
  titleLine: '다음엔 비슷한 상황에서\n한 번 더 생각해볼 것 같아요.',
  totalCount: 20,
  totalAmount: 534000,
  avgSatisfactionComment: '결과적으로는 돈 쓴 보람이 크진 않았어요.',
  categories: [
    {
      id: 'impulsive',
      rank: 1,
      name: '홀린 듯한 소비',
      state: 'expanded',
      description: '크게 후회는 없지만, 엄청 잘 썼다는 느낌도 아니에요.',
      satisfactionRows: [
        { level: 5, label: '정말 만족했어요', count: 3, totalAmount: 180000 },
        { level: 4, label: '대체로 만족했어요', count: 1, totalAmount: 9000 },
        { level: 3, label: '그냥 그랬어요', count: 3, totalAmount: 120000 },
        { level: 2, label: '조금 아쉬워요', count: 0, totalAmount: 0 },
        { level: 1, label: '별로였어요', count: 2, totalAmount: 50000 },
      ],
      totalCount: 9,
      totalAmount: 359000,
    },
    {
      id: 'survival',
      rank: 2,
      name: '살기 위한 소비',
      state: 'expanded',
      description: '다시 돌아보면 조금 말리고 싶은 선택이에요.',
      satisfactionRows: [
        { level: 5, label: '정말 만족했어요', count: 2, totalAmount: 45000 },
        { level: 4, label: '대체로 만족했어요', count: 1, totalAmount: 9000 },
        { level: 3, label: '그냥 그랬어요', count: 3, totalAmount: 60000 },
        { level: 2, label: '조금 아쉬워요', count: 0, totalAmount: 0 },
        { level: 1, label: '별로였어요', count: 2, totalAmount: 50000 },
      ],
      totalCount: 8,
      totalAmount: 164000,
    },
    {
      id: 'essential',
      rank: 3,
      name: '필수템 소비',
      state: 'collapsed',
      description: '꼭 필요한 소비였어요.',
      satisfactionRows: [
        { level: 5, label: '정말 만족했어요', count: 1, totalAmount: 11000 },
        { level: 4, label: '대체로 만족했어요', count: 0, totalAmount: 0 },
        { level: 3, label: '그냥 그랬어요', count: 0, totalAmount: 0 },
        { level: 2, label: '조금 아쉬워요', count: 0, totalAmount: 0 },
        { level: 1, label: '별로였어요', count: 0, totalAmount: 0 },
      ],
      totalCount: 1,
      totalAmount: 11000,
    },
    {
      id: 'mood',
      rank: 4,
      name: '기분 전환 소비',
      state: 'collapsed',
      description: '기분 전환이 필요했던 소비예요.',
      satisfactionRows: [
        { level: 5, label: '정말 만족했어요', count: 2, totalAmount: 10000 },
        { level: 4, label: '대체로 만족했어요', count: 0, totalAmount: 0 },
        { level: 3, label: '그냥 그랬어요', count: 0, totalAmount: 0 },
        { level: 2, label: '조금 아쉬워요', count: 0, totalAmount: 0 },
        { level: 1, label: '별로였어요', count: 0, totalAmount: 0 },
      ],
      totalCount: 2,
      totalAmount: 10000,
    },
    {
      id: 'neutral',
      rank: 5,
      name: '그냥저냥한 소비',
      state: 'disabled',
      description: '',
      satisfactionRows: [],
      totalCount: 0,
      totalAmount: 0,
    },
  ],
};
