name: CI - 빌드 및 린트 테스트

on: [pull_request]

jobs:
  check-types:
    if: |
      github.actor == 'hyun907' ||
      github.actor == 'ssilver01'

    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 및 pnpm 설치
        uses: ./.github/actions/setup-node-pnpm

      - name: 의존성 설치
        run: pnpm install --frozen-lockfile

      - name: 타입 체크
        run: pnpm check-types

  lint:
    if: |
      github.actor == 'hyun907' ||
      github.actor == 'ssilver01'

    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 및 pnpm 설치
        uses: ./.github/actions/setup-node-pnpm

      - name: 의존성 설치
        run: pnpm install --frozen-lockfile

      - name: 린트 체크
        run: pnpm lint

      - name: 코드 포맷 체크
        run: pnpm prettier

  build:
    if: |
      github.actor == 'hyun907' ||
      github.actor == 'ssilver01'

    needs: [check-types, lint]
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 및 pnpm 설치
        uses: ./.github/actions/setup-node-pnpm

      - name: 의존성 설치
        run: pnpm install --frozen-lockfile

      - name: 빌드 실행
        run: pnpm build
